name: Update Leaderboard

on:
  schedule:
    - cron: "0 */2 * * *" # 2 hour backup (in case vercel down or smth else)
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping API
        run: curl -sS https://mini-juz.vercel.app/api/update-board
